sudo: required
services:
  - docker

before_install:
  - docker build -t heet1996/my-profile -f Dockerfile.dev .

script:
  - docker run heet1996/my-profile npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "My-profile"
  env: "MyProfile-env"
  bucket_name: "elasticbeanstalk-us-east-1-413920612934"
  bucket_path: "My-profile"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
    
